services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    command:
      - azurite-blob
      - --blobHost
      - "0.0.0.0"
      - --blobPort
      - "10000"
      - --skipApiVersionCheck
    ports:
      - "10000:10000"   # Blob